".local/bin/update-vscode":
  type:       "file"
  url:        "https://raw.githubusercontent.com/0x5c/dotfiles/0cfe8b1bad16342b55bfe8cf543befcad905c4e0/exact_utils/vscode/executable_update-vscode.py"
  executable: true

".local/share/nvim/site/autoload/plug.vim":
  type:           "file"
  url:            "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod:  "168h"

##########################################################################################
##### zsh plugins

".local/share/zsh/autoswitch_virtualenv.plugin.zsh":
  type: "file"
  url:  "https://raw.githubusercontent.com/MichaelAquilina/zsh-autoswitch-virtualenv/master/autoswitch_virtualenv.plugin.zsh"
  refreshPeriod: "168h"

".local/share/zsh/fancy-ctrl-z-mode.plugin.zsh":
  type: "file"
  url:  "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh"
  refreshPeriod: "168h"

".local/share/zsh/zsh-not-vim/":
  type: "git-repo"
  url:  "https://github.com/redxtech/zsh-not-vim.git"
  refreshPeriod: "168h"

".local/share/zsh/zsh-syntax-highlighting/":
  type: "git-repo"
  url:  "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  refreshPeriod: "168h"

".local/share/zsh/zsh-vi-mode/":
  type: "git-repo"
  url:  "https://github.com/jeffreytse/zsh-vi-mode.git"
  refreshPeriod: "168h"
