".local/share/nvim/site/autoload/plug.vim":
  type:           "file"
  url:            "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod:  "168h"

".local/bin/update-vscode":
  type:       "file"
  url:        "https://raw.githubusercontent.com/0x5c/dotfiles/0cfe8b1bad16342b55bfe8cf543befcad905c4e0/exact_utils/vscode/executable_update-vscode.py"
  executable: true
