".local/share/nvim/site/autoload/plug.vim":
  type:           "file"
  url:            "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod:  "168h"

##########################################################################################
##### zsh plugins

".local/share/zsh_plugins/autoswitch_virtualenv.plugin.zsh":
  type: "file"
  url:  "https://raw.githubusercontent.com/MichaelAquilina/zsh-autoswitch-virtualenv/master/autoswitch_virtualenv.plugin.zsh"
  refreshPeriod: "168h"

".local/share/zsh_plugins/fancy-ctrl-z-mode.plugin.zsh":
  type: "file"
  url:  "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/fancy-ctrl-z/fancy-ctrl-z.plugin.zsh"
  refreshPeriod: "168h"

".local/share/zsh_plugins/zsh-not-vim/":
  type: "git-repo"
  url:  "https://github.com/redxtech/zsh-not-vim.git"
  refreshPeriod: "168h"

".local/share/zsh_plugins/zsh-syntax-highlighting/":
  type: "git-repo"
  url:  "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  refreshPeriod: "168h"

".local/share/zsh_plugins/zsh-vi-mode/":
  type: "git-repo"
  url:  "https://github.com/jeffreytse/zsh-vi-mode.git"
  refreshPeriod: "168h"
