[tool.black]
line-length = 90
target-version = ["py310", "py311"]
skip-magic-trailing-comma = true
# not all python files are marked as such
include = "dot_local/bin/executable_wg-random"

[tool.isort]
line_length = 90
profile = "black"
