# dev tools
[tool.ruff]
line-length     = 90
indent-width    = 4
target-version  = "py312"

[tool.ruff.format]
docstring-code-format = true
line-ending = "lf"
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
line_length = 90

[tool.black]
line-length = 90
target-version = ["py312"]
skip-magic-trailing-comma = true
# not all python files are marked as such
include = "dot_local/bin/executable_wg-random"
