#!/bin/zsh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

. ~/.config/zsh/00_path.zsh
for file in ~/.config/zsh/10_*.zsh(.); do
    . "$file"
done

if command -v "startplasma-x11" &>/dev/null; then
    exec dbus-launch --exit-with-session startplasma-x11
fi
