#!/bin/sh


# xfree86 is fucking stupid
xmodmap -e "keycode 191 = F13"
xmodmap -e "keycode 192 = F14"
xmodmap -e "keycode 193 = F15"
xmodmap -e "keycode 194 = F16"


if command -v pipewire; then
    # if these processes are already being used, it's ok,
    # pipewire will stop automatically anyways
    pipewire &
    # black magick: pipewire is VERY unhappy with spawning `pipewire-pulse` & `wireplumber` manually.
    # May8e it does this already? I don't know.
fi
