.TH GIT-CAP 1 2024-02-06 v1.0
.SH NAME
git-cap -
.IR C ommit
.IR A dd
.IR P atch
.SH SYNOPSIS
.BR "git cap " [...]
.SH DESCRIPTION
.B git cap
stages all files with the
.B --patch
flag and prepares a commit with the specified arguments.
.PP
.B git cap
achieves this by resetting the working tree, tracking every file in the
.B git
repository, and finally preparing a commit with the given flags.

For example,
    git cap -m 'Initial commit'

interactively prompts you to select all new hunks, stages them, and prepares a
commit with the message "Initial commit".
